import Head from "next/head";
import { Inbox } from "@trycourier/react-inbox";
import { useEffect, useState } from "react";

export default function Home() {
  const [isReady, setReady] = useState(false);
  const [message, setMessage] = useState("");

  async function sendNotification() {
    await fetch("/api/sendNotification", {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify({ message }),
    });
    setMessage("");
  }

  useEffect(() => {
    setReady(true);
  }, []);
  return (
    <div>
      <Head>
        <title>FB like Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header
          style={{
            display: "flex",
            padding: "0 20px",
            background: "#00b1f4",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <h1>FB Notification</h1>
          {isReady && <Inbox />}
        </header>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <textarea
            placeholder="Notification message"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            cols={30}
            rows={5}
            style={{ margin: "20px auto" }}
          />
          <button onClick={sendNotification}>Send Notification</button>
        </div>
      </main>
    </div>
  );
}
